[project]
name = "homework-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=2.2.5",
    "torch>=2.7.0",
]
